import {useEffect,useState} from "react";
import {BarChart3,Bell,CalendarDays,CheckCircle2,Home,LogOut,Plus,Users,WalletCards} from "lucide-react";
const API=import.meta.env.VITE_API_URL||"http://localhost:8000";
const auth=()=>({Authorization:`Bearer ${localStorage.getItem("token")}`});

export default function App(){
 const [user,setUser]=useState(null),[page,setPage]=useState("dashboard"),[error,setError]=useState("");
 const load=async()=>{const r=await fetch(API+"/api/me",{headers:auth()});if(r.ok)setUser(await r.json());else localStorage.removeItem("token")};
 useEffect(()=>{if(localStorage.getItem("token"))load()},[]);
 useEffect(()=>{window.scrollTo({top:0,behavior:"auto"});setError("")},[page]);
 if(!localStorage.getItem("token"))return <Login onDone={load}/>;
 if(!user)return <div className="center">Loading your account…</div>;
 const logout=()=>{localStorage.removeItem("token");location.reload()};
 return <div className="shell"><aside><div className="brand"><Home/> Akshar Purushottam Chhatralay</div><nav>
  <button className={page==="dashboard"?"active":""} onClick={()=>setPage("dashboard")}><WalletCards/>Dashboard</button>
  <button className={page==="activities"?"active":""} onClick={()=>setPage("activities")}><CalendarDays/>Activities & votes</button>
  <button className={page==="payments"?"active":""} onClick={()=>setPage("payments")}><WalletCards/>Payments</button>
  {user.role==="admin"&&<button className={page==="collections"?"active":""} onClick={()=>setPage("collections")}><BarChart3/>Collections</button>}
  {user.role==="admin"&&<button className={page==="tenants"?"active":""} onClick={()=>setPage("tenants")}><Users/>Tenants</button>}
  {user.role==="admin"&&<button className={page==="add-tenant"?"active":""} onClick={()=>setPage("add-tenant")}><Plus/>Add tenant</button>}
  {user.role==="tenant"&&<button className={page==="my-details"?"active":""} onClick={()=>setPage("my-details")}><Users/>My details</button>}
  {user.role==="admin"&&<button className={page==="recipients"?"active":""} onClick={()=>setPage("recipients")}><Bell/>Email recipients</button>}
 </nav><button onClick={logout} aria-label="Sign out"><LogOut/>Sign out</button></aside>
 <main><header><div><small>{user.role.toUpperCase()}</small><h1>Welcome, {user.name}</h1></div><Bell/></header>
 {error&&<div className="error">{error}</div>}
 {page==="activities"?<Activities user={user} setError={setError}/>:page==="tenants"&&user.role==="admin"?<Tenants setError={setError}/>:page==="add-tenant"&&user.role==="admin"?<AddTenant setError={setError}/>:page==="my-details"&&user.role==="tenant"?<MyDetails setError={setError}/>:page==="collections"&&user.role==="admin"?<Collections setError={setError}/>:page==="payments"?<Payments user={user} setError={setError} reloadUser={load}/>:page==="recipients"&&user.role==="admin"?<Recipients setError={setError}/>:user.role==="admin"?<AdminDashboard/>:<TenantDashboard user={user}/>}
 </main></div>
}

function Login({onDone}){
 const [register,setRegister]=useState(false),[error,setError]=useState("");
 async function submit(e){e.preventDefault();const f=new FormData(e.currentTarget);let r;
  if(register)r=await fetch(API+"/api/auth/register",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(f))});
  else{const body=new URLSearchParams();body.set("username",f.get("email"));body.set("password",f.get("password"));r=await fetch(API+"/api/auth/login",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body})}
  const d=await r.json();if(!r.ok)return setError(d.detail||"Could not sign in");localStorage.setItem("token",d.access_token);onDone()}
 return <div className="login"><div className="login-card"><div className="brand"><Home/> Akshar Purushottam Chhatralay</div><h1>{register?"Verify email and create account":"Sign in"}</h1><p>{register?"Enter the email saved by your housing administrator and the code emailed to that address. Your account is created only after the code is verified.":"View rent, activities and voting."}</p>{error&&<div className="error">{error}</div>}<form onSubmit={submit}>{register&&<Field name="full_name" label="Full name" autoComplete="name"/>}<Field name="email" label="Email" type="email" autoComplete="email"/><Field name="password" label="Password" type="password" autoComplete={register?"new-password":"current-password"}/>{register&&<Field name="invite_code" label="Email verification code" autoComplete="one-time-code"/>}<button className="primary">{register?"Verify and create account":"Sign in"}</button></form><button className="link" onClick={()=>{setRegister(!register);setError("")}}>{register?"Already registered? Sign in":"Tenant? Create your account"}</button></div></div>
}
const Field=({name,label,type="text",...p})=><label>{label}<input name={name} type={type} required {...p}/></label>;

function TenantDashboard({user}){
 const t=user.tenant;if(!t)return <Empty title="Your tenant profile is not linked" text="Ask the administrator to check the email on your resident record."/>;
 return <><div className="cards"><Card title="Outstanding balance" value={aud(t.balance)} tone={t.balance>0?"warn":"ok"}/><Card title="Weekly rent" value={aud(t.weekly_rent)}/><Card title="Room" value={t.room}/></div><section><h2>Your rent history</h2>{!t.charges.length?<Empty title="No rent charges yet" text="New charges will appear here."/>:<table><thead><tr><th>Due date</th><th>Charge</th><th>Paid</th><th>Balance</th></tr></thead><tbody>{t.charges.map(c=><tr key={c.id}><td>{c.due_date}</td><td>{aud(c.amount)}</td><td>{aud(c.paid)}</td><td className={c.balance>0?"due":""}>{aud(c.balance)}</td></tr>)}</tbody></table>}</section></>
}
function AdminDashboard(){
 const [d,setD]=useState(null),[message,setMessage]=useState("");
 const load=()=>fetch(API+"/api/admin/dashboard",{headers:auth()}).then(r=>r.json()).then(setD);
 async function chargeEveryone(e){e.preventDefault();const form=e.currentTarget;const due_date=new FormData(form).get("due_date");if(!confirm(`Create a rent charge for every active tenant due on ${due_date}? Each person's saved weekly rent will be used.`))return;setMessage("");try{const r=await fetch(API+"/api/admin/charges/all",{method:"POST",headers:{...auth(),"Content-Type":"application/json"},body:JSON.stringify({due_date})});const data=await r.json();if(!r.ok)throw Error(data.detail||"Could not create rent charges");setMessage(`${data.created} rent charges created. Email notices have been queued; check Render logs if an email does not arrive.`);form.reset();await load()}catch(e){setMessage(e.message)}}
 useEffect(()=>{void load()},[]);
 if(!d)return <div>Loading…</div>;
 return <><div className="cards"><Card title="Total active tenants" value={d.tenants.length}/><Card title="Tenants with outstanding rent" value={d.pending.length} tone="warn"/><Card title="Total outstanding" value={aud(d.total_outstanding)} tone="warn"/></div>{message&&<p role="status">{message}</p>}<section><h2>Charge all active tenants</h2><p className="muted">Choose a due date. Each tenant is charged their saved weekly rent and an email notice is queued.</p><form className="grid-form" onSubmit={chargeEveryone}><Field name="due_date" label="Rent due date" type="date"/><button className="primary">Create charges for everyone</button></form></section><details className="panel"><summary>View outstanding rent ({d.pending.length})</summary>{!d.pending.length?<p>No outstanding rent.</p>:<div className="table-scroll"><table><thead><tr><th>Tenant</th><th>Room</th><th>Outstanding</th></tr></thead><tbody>{d.pending.map(t=><tr key={t.id}><td>{t.name}</td><td>{t.room}</td><td className="due">{aud(t.balance)}</td></tr>)}</tbody></table></div>}</details><details className="panel"><summary>Charge one tenant</summary><ChargeForm tenants={d.tenants} reload={load}/></details></>
}

function ProfileDetails({profile,showPayments=false}){
 const p=profile;
 return <><dl className="tenant-details"><dt>Name</dt><dd>{p.full_name}</dd><dt>Tenant number</dt><dd>{p.id}</dd><dt>Email</dt><dd>{p.email}</dd><dt>Phone</dt><dd>{p.phone||"—"}</dd><dt>Room</dt><dd>{p.room}</dd><dt>Current address</dt><dd>{p.current_address||"—"}</dd><dt>Move-in date</dt><dd>{p.move_in_date}</dd><dt>Weekly rent</dt><dd>{aud(p.weekly_rent)}</dd><dt>Bond</dt><dd>{aud(p.bond_amount)}</dd><dt>Reference name</dt><dd>{p.reference_name||"—"}</dd><dt>Reference phone</dt><dd>{p.reference_phone||"—"}</dd><dt>Reference email</dt><dd>{p.reference_email||"—"}</dd><dt>Account</dt><dd>{p.registered?"Registered":"Not registered"}</dd></dl><h3>Rent charges</h3>{!p.charges.length?<p>No rent charges yet.</p>:<table><thead><tr><th>Due date</th><th>Amount</th><th>Paid</th><th>Note</th></tr></thead><tbody>{p.charges.map(c=><tr key={c.id}><td>{c.due_date}</td><td>{aud(c.amount)}</td><td>{aud(c.paid)}</td><td>{c.note}</td></tr>)}</tbody></table>}{showPayments&&<><h3>Payment submissions</h3>{!p.payments.length?<p>No payments submitted yet.</p>:<table><thead><tr><th>Date</th><th>Amount</th><th>Bank reference</th><th>Status</th></tr></thead><tbody>{p.payments.map(payment=><tr key={payment.id}><td>{payment.payment_date}</td><td>{aud(payment.amount)}</td><td>{payment.bank_reference}</td><td>{payment.state}</td></tr>)}</tbody></table>}</>}</>
}

function Tenants({setError}){
 const [items,setItems]=useState(null),[selected,setSelected]=useState(null);
 const [loading,setLoading]=useState(false),[query,setQuery]=useState(""),[showArchived,setShowArchived]=useState(false);
 const visible=items?.filter(t=>(showArchived||t.is_active)&&`${t.name} ${t.room} ${t.email}`.toLowerCase().includes(query.toLowerCase()))||[];
 const load=async()=>{const r=await fetch(API+"/api/admin/tenants",{headers:auth()});const data=await r.json();if(!r.ok)throw Error(data.detail||"Could not load tenants");setItems(data)};
 useEffect(()=>{void load().catch(e=>setError(e.message))},[setError]);
 async function openTenant(id){setLoading(true);setError("");try{const r=await fetch(API+`/api/admin/tenants/${id}`,{headers:auth()});const data=await r.json();if(!r.ok)throw Error(data.detail||"Could not load tenant details");setSelected(data)}catch(e){setError(e.message)}finally{setLoading(false)}}
 async function updateStatus(action){if(!selected)return;const active=action==="archive";if(active&&!confirm(`Remove ${selected.full_name} from active tenants? Their payment records will be kept.`))return;
  setLoading(true);setError("");try{const r=await fetch(API+`/api/admin/tenants/${selected.id}/${action}`,{method:"POST",headers:auth()});const data=await r.json();if(!r.ok)throw Error(data.detail||"Could not update tenant");setSelected(null);await load()}catch(e){setError(e.message)}finally{setLoading(false)}}
 async function resend(t){try{const r=await fetch(API+`/api/admin/tenants/${t.id}/invite`,{method:"POST",headers:auth()});const data=await r.json();if(!r.ok)throw Error(data.detail||"Could not send code");alert(`Verification code queued for ${t.email}. Check delivery in Render logs.`)}catch(e){setError(e.message)}}
 const outstanding=selected?.charges.reduce((total,c)=>total+Math.max(0,c.amount-c.paid),0)||0;
 const pending=selected?.payments.some(p=>p.state==="pending")||false;
 if(selected)return <section className="tenant-profile"><button className="link" onClick={()=>setSelected(null)}>← All tenants</button><h2>{selected.full_name}</h2><p className="muted">{selected.is_active?"Active tenant":"Archived tenant"}</p><ProfileDetails profile={selected} showPayments/>
  <div className="profile-actions">{selected.is_active?<><button className="danger" disabled={loading||outstanding>0||pending} onClick={()=>updateStatus("archive")}>Remove tenant</button>{outstanding>0&&<p>Removal is available after all rent is paid. Outstanding: {aud(outstanding)}.</p>}{pending&&<p>Review pending payment submissions before removal.</p>}</>:<button className="primary" disabled={loading} onClick={()=>updateStatus("restore")}>Restore tenant</button>}</div>
 </section>;
 return <section><h2>Tenants</h2><p className="muted">Select a name to see its saved details and payment history.</p><div className="tenant-filters"><label className="tenant-search">Search tenants<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name, room or email"/></label><label className="checkbox"><input type="checkbox" checked={showArchived} onChange={e=>setShowArchived(e.target.checked)}/> Show archived</label></div>
 {items===null?<p>Loading tenants…</p>:!items.length?<p>No tenants added yet.</p>:!visible.length?<p>No matching tenants.</p>:<div className="table-scroll"><table><thead><tr><th>Name</th><th>Room</th><th>Email</th><th>Status</th><th>Registration</th></tr></thead><tbody>{visible.map(t=><tr key={t.id}><td><button className="tenant-name" onClick={()=>openTenant(t.id)}>{t.name}</button></td><td>{t.room}</td><td>{t.email}</td><td>{t.is_active?"Active":"Archived"}</td><td>{t.registered?"Registered":t.is_active?<button className="link" onClick={()=>resend(t)}>Send verification code</button>:"Not registered"}</td></tr>)}</tbody></table></div>}{loading&&<p>Loading tenant details…</p>}</section>
}

function Collections({setError}){
 const [year,setYear]=useState(new Date().getFullYear()),[data,setData]=useState(null);
 useEffect(()=>{let active=true;setData(null);fetch(API+`/api/admin/collections?year=${year}`,{headers:auth()}).then(async r=>{const body=await r.json();if(!r.ok)throw Error(body.detail||"Could not load collections");if(active)setData(body)}).catch(e=>setError(e.message));return()=>{active=false}},[year,setError]);
 const years=Array.from({length:11},(_,i)=>new Date().getFullYear()+1-i);
 return <><section><h2>Rent collected by tenant</h2><label className="year-picker">Year (1 January to 1 January)<select value={year} onChange={e=>setYear(Number(e.target.value))}>{years.map(y=><option key={y} value={y}>{y} — {y+1}</option>)}</select></label><p className="muted">For {year}, this report includes approved tenant submissions and dated manual payments from 1 January {year} through 31 December {year}. Pending or rejected submissions are excluded.</p>{!data?<p>Loading collections…</p>:<><div className="cards"><Card title="Total collected" value={aud(data.total)} tone="ok"/><Card title="Tenants in report" value={data.tenants.length}/></div><div className="table-scroll"><table><thead><tr><th>Tenant</th><th>Room</th><th>Collected</th></tr></thead><tbody>{data.tenants.map(t=><tr key={t.tenant_id}><td>{t.name}{!t.active&&" (archived)"}</td><td>{t.room}</td><td>{aud(t.collected)}</td></tr>)}</tbody></table></div>{data.historical_undated>0&&<p className="muted">{aud(data.historical_undated)} in older manually recorded payments has no payment date in the original app, so it cannot be assigned to a specific year.</p>}</>}</section></>
}

function MyDetails({setError}){
 const [profile,setProfile]=useState(null);
 useEffect(()=>{let active=true;fetch(API+"/api/me/profile",{headers:auth()}).then(async r=>{const data=await r.json();if(!r.ok)throw Error(data.detail||"Could not load your details");if(active)setProfile(data)}).catch(e=>setError(e.message));return()=>{active=false}},[setError]);
 return <section><h2>My details</h2>{profile?<><p className="muted">These details were saved by your housing administrator. Ask them if anything needs correcting.</p><ProfileDetails profile={profile} showPayments/></>:<p>Loading your details…</p>}</section>
}

function ChargeForm({tenants,reload}){async function submit(e){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);const r=await fetch(API+"/api/admin/charges",{method:"POST",headers:{...auth(),"Content-Type":"application/json"},body:JSON.stringify({tenant_id:+f.get("tenant_id"),due_date:f.get("due_date"),amount:+f.get("amount"),note:f.get("note")})});if(r.ok){form.reset();reload()}}
 return <section><h2>Add rent charge</h2><form className="grid-form" onSubmit={submit}><label>Tenant<select name="tenant_id" required>{tenants.map(t=><option value={t.id} key={t.id}>{t.name} — {t.room}</option>)}</select></label><Field name="due_date" label="Due date" type="date"/><Field name="amount" label="Amount (AUD)" type="number" step="0.01"/><Field name="note" label="Note"/><button className="primary">Add charge</button></form></section>}

function AddTenant({setError}){async function submit(e){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);const body=Object.fromEntries(f);body.weekly_rent=+body.weekly_rent;body.bond_amount=+body.bond_amount;const r=await fetch(API+"/api/admin/tenants",{method:"POST",headers:{...auth(),"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)return setError(d.detail);form.reset();alert("Tenant added. A registration code will be emailed to them.")}
 return <section><h2>Add tenant</h2><p className="muted">A registration code will be emailed to this tenant. Configure the email API in the backend first.</p><form className="grid-form" onSubmit={submit}><Field name="full_name" label="Full name"/><Field name="email" label="Email" type="email"/><Field name="phone" label="Phone"/><Field name="room" label="Room / unit"/><Field name="current_address" label="Current address"/><Field name="move_in_date" label="Move-in date" type="date"/><Field name="weekly_rent" label="Weekly rent" type="number" step="0.01"/><Field name="bond_amount" label="Bond amount" type="number" step="0.01"/><Field name="reference_name" label="Reference name"/><Field name="reference_phone" label="Reference phone"/><Field name="reference_email" label="Reference email" type="email"/><button className="primary">Save tenant</button></form></section>}

function Activities({user,setError}){const [items,setItems]=useState([]);const load=()=>fetch(API+"/api/activities",{headers:auth()}).then(r=>r.json()).then(setItems);useEffect(() => {
  void load();
}, []);
 async function add(e){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);const body={title:f.get("title"),description:f.get("description"),activity_date:f.get("activity_date"),poll_question:f.get("poll_question")||null,options:[f.get("option1"),f.get("option2"),f.get("option3")].filter(Boolean)};const r=await fetch(API+"/api/admin/activities",{method:"POST",headers:{...auth(),"Content-Type":"application/json"},body:JSON.stringify(body)});if(r.ok){form.reset();load()}}
 async function vote(poll,option){const r=await fetch(API+`/api/polls/${poll}/vote`,{method:"POST",headers:{...auth(),"Content-Type":"application/json"},body:JSON.stringify({option_id:option})});const d=await r.json();if(!r.ok)setError(d.detail);else load()}
 return <>{user.role==="admin"&&<section><h2>Post activity & poll</h2><form className="grid-form" onSubmit={add}><Field name="title" label="Activity title"/><Field name="activity_date" label="Date" type="date"/><Field name="description" label="Description"/><Field name="poll_question" label="Poll question (optional)"/><Field name="option1" label="Option 1"/><Field name="option2" label="Option 2"/><Field name="option3" label="Option 3 (optional)"/><button className="primary">Publish activity</button></form></section>}<section><h2>Activities</h2><div className="activity-list">{items.map(a=><article key={a.id}><div className="date">{a.date}</div><h3>{a.title}</h3><p>{a.description}</p>{a.poll&&<div className="poll"><strong>{a.poll.question}</strong>{a.poll.options.map(o=><button key={o.id} disabled={user.role!=="tenant"||!!a.poll.voted_option_id} onClick={()=>vote(a.poll.id,o.id)} className={a.poll.voted_option_id===o.id?"chosen":""}>{o.label}{user.role==="admin"&&` — ${o.votes} votes`}{a.poll.voted_option_id===o.id&&" ✓"}</button>)}</div>}</article>)}</div></section></>}

function Payments({user,setError,reloadUser}){
 const [items,setItems]=useState([]),[busy,setBusy]=useState(false);
 const endpoint=user.role==="admin"?"/api/admin/payments":"/api/payments";
 const load=async()=>{try{const r=await fetch(API+endpoint,{headers:auth()});if(!r.ok)throw Error("Could not load payments");setItems(await r.json())}catch(e){setError(e.message)}};
 useEffect(()=>{void load()},[endpoint]);
 async function submit(e){e.preventDefault();const form=e.currentTarget;const body=new FormData(form);const photo=body.get("receipt");if(photo?.size>2*1024*1024)return setError("Receipt must be under 2 MB");setBusy(true);setError("");try{
  const r=await fetch(API+"/api/payments",{method:"POST",headers:auth(),body});const data=await r.json();if(!r.ok)throw Error(data.detail||"Could not submit payment");form.reset();await load();
 }catch(e){setError(e.message)}finally{setBusy(false)}}
 async function review(p,decision){const note=decision==="rejected"?prompt("Reason for rejection (shown to tenant):"):"";if(note===null)return;setBusy(true);setError("");try{
  const r=await fetch(API+`/api/admin/payments/${p.id}/review`,{method:"POST",headers:{...auth(),"Content-Type":"application/json"},body:JSON.stringify({decision,note})});const data=await r.json();if(!r.ok)throw Error(data.detail||"Could not review payment");await load();await reloadUser();
 }catch(e){setError(e.message)}finally{setBusy(false)}}
 async function receipt(p){const tab=window.open("","_blank");if(!tab)return setError("Allow pop-ups to view the receipt");try{const r=await fetch(API+`/api/admin/payments/${p.id}/receipt`,{headers:auth()});if(!r.ok)throw Error("Could not open receipt");const url=URL.createObjectURL(await r.blob());tab.location.href=url;setTimeout(()=>URL.revokeObjectURL(url),60000)}catch(e){tab.close();setError(e.message)}}
 return <>{user.role==="tenant"&&<section><h2>Submit a rent payment</h2><p className="muted">Your tenant number is {user.tenant?.id}. Your balance changes after the admin verifies the transfer.</p><form className="grid-form" onSubmit={submit}><Field name="amount" label="Amount paid (AUD)" type="number" min="0.01" step="0.01"/><Field name="payment_date" label="Payment date" type="date"/><Field name="bank_reference" label="Bank transaction reference" maxLength="120"/><Field name="bank_details" label="Bank transfer details (optional; no account password)" required={false} maxLength="300"/><label>Receipt image (optional, JPG/PNG/WebP, max 2 MB)<input name="receipt" type="file" accept="image/jpeg,image/png,image/webp"/></label><button className="primary" disabled={busy}>Submit for review</button></form></section>}
 <section><h2>{user.role==="admin"?"Payment submissions":"My payment submissions"}</h2>{!items.length?<p className="muted">No payments submitted yet.</p>:<table><thead><tr>{user.role==="admin"&&<th>Tenant</th>}<th>Amount</th><th>Date</th><th>Bank reference</th><th>Details</th><th>Receipt</th><th>Status</th><th>Action</th></tr></thead><tbody>{items.map(p=><tr key={p.id}>{user.role==="admin"&&<td>{p.tenant_name} (#{p.tenant_id})</td>}<td>{aud(p.amount)}</td><td>{p.payment_date}</td><td>{p.bank_reference}</td><td>{p.bank_details}</td><td>{user.role==="admin"&&p.has_receipt?<button className="link" onClick={()=>receipt(p)}>View image</button>:p.has_receipt?"Attached":"—"}</td><td>{p.state}{p.review_note&&<small> — {p.review_note}</small>}</td><td>{user.role==="admin"&&p.state==="pending"?<div className="actions"><button disabled={busy} onClick={()=>review(p,"approved")}>Approve</button><button disabled={busy} onClick={()=>review(p,"rejected")}>Reject</button></div>:"—"}</td></tr>)}</tbody></table>}</section></>
}

function Recipients({setError}){
 const [items,setItems]=useState([]);
 const load=async()=>{try{const r=await fetch(API+"/api/admin/notification-recipients",{headers:auth()});if(!r.ok)throw Error("Could not load recipients");setItems(await r.json())}catch(e){setError(e.message)}};
 useEffect(()=>{void load()},[]);
 async function add(e){e.preventDefault();const form=e.currentTarget;const email=new FormData(form).get("email");setError("");try{const r=await fetch(API+"/api/admin/notification-recipients",{method:"POST",headers:{...auth(),"Content-Type":"application/json"},body:JSON.stringify({email})});const d=await r.json();if(!r.ok)throw Error(d.detail||"Could not add recipient");form.reset();await load()}catch(e){setError(e.message)}}
 async function remove(id){if(!confirm("Remove this email recipient?"))return;const r=await fetch(API+`/api/admin/notification-recipients/${id}`,{method:"DELETE",headers:auth()});if(r.ok)await load();else setError("Could not remove recipient")}
 async function changePassword(e){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);setError("");try{const r=await fetch(API+"/api/me/change-password",{method:"POST",headers:{...auth(),"Content-Type":"application/json"},body:JSON.stringify({old_password:f.get("old_password"),new_password:f.get("new_password")})});const d=await r.json();if(!r.ok)throw Error(d.detail||"Could not change password");form.reset();alert("Password changed") }catch(e){setError(e.message)}}
 return <><section><h2>Additional email recipients</h2><p className="muted">Only add people authorized to receive tenant payment updates. Receipts are viewable by admins in the app and are never attached to email.</p><form className="grid-form" onSubmit={add}><Field name="email" label="Email address" type="email"/><button className="primary">Add recipient</button></form><table><tbody>{items.map(r=><tr key={r.id}><td>{r.email}</td><td><button className="link" onClick={()=>remove(r.id)}>Remove</button></td></tr>)}</tbody></table></section><section><h2>Change admin password</h2><form className="grid-form" onSubmit={changePassword}><Field name="old_password" label="Current password" type="password" autoComplete="current-password"/><Field name="new_password" label="New password (at least 12 characters)" type="password" minLength="12" autoComplete="new-password"/><button className="primary">Change password</button></form></section></>
}
const Card=({title,value,tone=""})=><div className={`card ${tone}`}><small>{title}</small><b>{value}</b></div>;
const Empty=({title,text})=><div className="empty"><CheckCircle2/><b>{title}</b><p>{text}</p></div>;
const aud=n=>new Intl.NumberFormat("en-AU",{style:"currency",currency:"AUD"}).format(n||0);
