services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: haven
      POSTGRES_USER: haven
      POSTGRES_PASSWORD: haven_local_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U haven -d haven"]
      interval: 5s
      timeout: 5s
      retries: 10
  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql+psycopg://haven:haven_local_password@db:5432/haven
      SECRET_KEY: 1csdlcnd-4rsdcckjrnkv3435935scd
      ADMIN_EMAIL: vithanivyom2@gmail.com
      ADMIN_PASSWORD: Akshar@purushottam$1109
      FRONTEND_URLS: http://192.168.0.236
    ports: ["8000:8000"]
    depends_on:
      db:
        condition: service_healthy
  frontend:
    build: ./frontend
    restart: unless-stopped
    environment:
      VITE_API_URL: http://192.168.0.236
    ports: ["5173:5173"]
    depends_on: [backend]
volumes:
  postgres_data:
